Task1
stepler/tasks-set pull request #1
Opened 2022-04-04 12:56 UTC by somebody-kseny

В 2х задачах дописала тесты для удобства

2022-04-04 15:33 UTC, stepler requested changes

2022-04-04 15:33 UTC, stepler commented on tasks/group-by.ts
> +        return fnRes;
В целом норм, но выглядит сложно и запутано.
Давай попробуем упростить
1 — измени порядок вложенности (сначала элементы потом предикаты)

2 — в таких тулзах лучше не использовать map / foreach. Проще и нагляднее всегда просто `for`

2022-04-04 15:33 UTC, stepler commented on tasks/range.ts
> +    for (let i = a; limit(i); i += step) {
попробуй избавится от функции в limit — вызов функции дело дорогое, а в таких тулзах нужно думать о скорости

2022-04-04 15:33 UTC, stepler commented on tasks/range.ts
> +        step = b-a > 0
`b-a > 0` — сложно
`b > a` — просто

2022-04-04 15:33 UTC, stepler commented on tasks/shuffle.ts
> +        set.add(Math.floor(Math.random() * arr.length));
тут ошибки
1 — `Math.floor(Math.random() * arr.length)` может / будет генерировать дублирующие id, а значит и терять часть данных исходного массива.
2 — Set не сохраняет дубликаты, опять теряешь данные

2022-04-04 15:33 UTC, stepler commented on tasks/shuffle.ts
> +        set.add(Math.floor(Math.random() * arr.length));
В целом подумай над алгоритмом выбора случайного

2022-04-04 15:33 UTC, stepler commented on tasks/shuffle.ts
> +    set.forEach((el) => {
тут проще и нагляднее сделать через `for`

2022-04-04 15:33 UTC, stepler commented on tasks/shuffle.ts
> +    set.forEach((el) => {
различные глобальные счетчики это зло, которое порой необходимо, но когда можно, лучше без них

2022-04-04 15:39 UTC, somebody-kseny commented on tasks/shuffle.ts
> +        set.add(Math.floor(Math.random() * arr.length));
Вроде из-за while (set.size < arr.length) данные не теряются, он генерит пока не нагенерирует все уникальные.
Но это просто спор ради спора, согласна что вцелом не круто.

2022-04-06 13:18 UTC, stepler commented on tasks/shuffle.ts
> +        set.add(Math.floor(Math.random() * arr.length));
Они точно теряются т.к. ты можешь сгенерить два одинаковых id (т.е. вытеснить/потерять исходный)

2022-04-07 12:44 UTC, stepler approved these changes

2022-04-07 12:44 UTC, stepler commented on tasks/shuffle.ts
> +    return Array.from(arr).sort(() => 0.5 - Math.random());
Очень круто, без шуток!
Тут `O(N log N)`.

А за `O(N)` можешь сделать?
Иными словами придумать алгоритм где шаффлиш массив за 1 проход по нему.

2022-04-07 12:44 UTC, stepler commented on tasks/group-by.ts
> +    fns.push(() => true);
ты мутируешь входной массив — это не оч гуд.

2022-04-08 10:53 UTC, somebody-kseny commented on tasks/shuffle.ts
> +    return Array.from(arr).sort(() => 0.5 - Math.random());
Эх, без подсказки не могу, получается.

2022-04-09 11:04 UTC, stepler commented on tasks/shuffle.ts
> +        res[i] = swap;
Почти идеальный вариант.

Еще можно избавится от одной операции (тройного присваивания) и переменной своп, делая два или одно присваивание.

В общем чуть хитрее ставить рандомный элемент меньшим кол-вом операций на стройках L7-L9.

Подумай как.

2022-04-09 11:04 UTC, stepler commented on tasks/shuffle.ts
> +    res[0] = arr[0];
еще это можно убрать и начинать итерацию с 0.
первая операция будет "холостая" но ничего страшного.

2022-04-13 13:04 UTC, closed without merging