Task2
stepler/tasks-set pull request #3
Opened 2022-04-21 12:52 UTC by somebody-kseny

Посмотри пожалуйста сначала тесты - к двум задачам исправила как мне показалось ошибки

2022-04-21 12:55 UTC, somebody-kseny commented on array/move.ts
> +    list.splice(to, 0, el);
судя по комментариям к прошлому паку задач, splice надо бы избегать. Но мне показалось, он тут сильно упрощает дело.

2022-04-21 14:52 UTC, stepler commented on array/move.ts
> +    list.splice(to, 0, el);
конено упрощает, но нужна своя реализация)

2022-04-21 14:58 UTC, stepler requested changes

2022-04-21 14:58 UTC, stepler commented on array/swap.ts
> +        b += list.length;
тут и выше не проверяется что после такого, b может быть < 0

2022-04-21 14:58 UTC, stepler commented on array/swap.ts
> +        b += list.length;
\+ тебе не кажется, что все преобразования с индексами тут и выше — это дубликаты?

2022-04-21 14:58 UTC, stepler commented on function/sequence-generator.ts
> +    return () => initial += step;
Отлично!

2022-04-26 14:44 UTC, stepler requested changes

2022-04-26 14:44 UTC, stepler commented on array/move.test.ts
> +        expect(move([1, 2, 3, 4, 5], 4, 2)).toEqual([1, 2, 5, 3, 4]); // ??
ошибся, комент можно убрать

2022-04-26 14:44 UTC, stepler commented on array/move.ts
> +}
1 — зачем каждый раз дублировать функцию? почему не вынести ее в какие-нить тузы и импортить?

2 — сложная реализация. 
Ты экономишь передачу 1 аргумента делая объект чекера.
К тому же это не столько чекер сколько нормализатор.

2022-04-26 14:44 UTC, stepler commented on array/slice.ts
> +    if (to > list.length) {
тут как буд-то тоже сначала нужен чекер/нормализатор

2022-04-26 14:44 UTC, stepler commented on array/move.ts
> +        list[i] = list[i + step];
как-то очень сложно, нужно упростить — убрать отрицательные step'ы и избавится от тернарной проверки

2022-04-26 14:44 UTC, stepler commented on array/slice.test.ts
> +        expect(slice(list, -3)).toEqual([3, 4, 5]); // ?
все так, ошибся (

2022-05-04 07:53 UTC, stepler requested changes
Давай еще вольем первый ПР)

2022-05-04 07:53 UTC, stepler commented on array/array-tools.ts
> +    if (i > len || i < -len) {
Проверка выглядит сложно.
Но если сначала проверить на i < 0 и преобразовать. то все упроститься

2022-05-04 07:53 UTC, stepler commented on array/slice.ts
> +    if (from > list.length) {
а нормализация разве это не проверить?

2022-05-04 07:53 UTC, stepler commented on array/slice.ts
> +    } else {
тут как-то переусложнены проверки имхо
если сначала в прогнать нормализацию а после проверять всякие корнер-кейсы, проще не будет?

2022-05-04 07:53 UTC, stepler commented on array/array-tools.ts
> +export const normalizeIndex = (i: number, len: number): number => {
мелочь, но я бы вторым аргументом передавал весь массив.
тогда функция станет органичней, т.к. сейчас мы тут оперируем абстрактными интами, и то что по факту проверяются данные массива (индексы) следует только из названия

2022-05-04 07:53 UTC, stepler commented on array/move.ts
> +    if (to < from) {
хочется немного упростить
```
const start = to < from ? to : from;
const end = to < from ? from : to;
`

2022-05-06 11:22 UTC, somebody-kseny commented on array/array-tools.ts
> +    if (i > len || i < -len) {
мне кажется что не упростится: все равно то же самое нужно проверять и возвращать ошибку (-1), например если передали сильно отрицательное число.

2022-05-06 11:25 UTC, somebody-kseny commented on array/move.ts
> +    if (to < from) {
Тоже кажется что так нельзя 👀
Если так делать, получается не важен порядок переданных аргументов. Но это неверно, разные результаты получаются, сдвиг в разные стороны нужен. Так что в цикле i+1/ i-1 должны оба сохраниться

2022-05-06 11:32 UTC, somebody-kseny commented on array/slice.ts
> +    if (from > list.length) {
Здесь дело в том, что в первом if возвращается пустой массив, а если из-за другого нормализация не прошла, то исходный

2022-05-06 11:34 UTC, somebody-kseny commented on array/slice.ts
> +    } else {
Здесь первый if дополнительная логика, которую я почему-то добавила, она не требуется тестами. Она может показаться странной вообще, удалила ее

2022-05-06 12:53 UTC, stepler commented on array/array-tools.ts
> +    if (i > len || i < -len) {
Конкретно тут это вкусовщина, но имхо так читабельнее, т.к. -arr.length конкретно меня сильно заставляет думать

```js
if (i < 0) {
    i += arr.length;
}

if (0 <= i && i < arr.length) { // читается как  `0 <= i < arr.length`
    return i;
}

return -1;

2022-05-06 12:56 UTC, stepler commented on array/slice.ts
> +    if (from > list.length) {
Вот не очень понятно зачем исходный возвращать.
Если мы задали невозможные границы — это пустой массив имхо.

2022-05-06 12:56 UTC, stepler commented on array/slice.ts
> +    if (from > list.length) {
И еще
```js
to = to || list.length;
to = normalizeIndex(to, list);
```
заменяется на `to = normalizeIndex(to || list.length, list);`

```js
const len = to - from;
if (len <= 0) {
    return [];
}
```
заменяется на `const len = Math.max(0, to - from);`

2022-05-06 12:57 UTC, stepler commented on array/slice.ts
> +    if (from > list.length) {
И тогда вся фиункция сильно сокращается и упрощается

2022-05-06 12:57 UTC, stepler commented on array/move.ts
> +    if (to < from) {
Да, тут не доглядел. Оставляем так

2022-05-06 13:58 UTC, somebody-kseny commented on array/array-tools.ts
> +export const normalizeAfterIndex = (i: number, arr: any[]): number => {
Пришлось сделать вторую функцию. На самом деле она и раньше была нужна. (Проверяется тестом slice base  ```expect(slice(list, 2, 5)).toEqual([3, 4, 5]);```)

Или можно вернуться к передаче длины и пердавать arr.length+1 в старую функцию (возле 0 что происходит не имеет значения в нашем случае)

2022-05-06 14:11 UTC, stepler commented on array/array-tools.ts
> +export const normalizeAfterIndex = (i: number, arr: any[]): number => {
Выглядит как большой костыль(
Для чего она нам, сходу не понял?

2022-05-23 14:22 UTC, merged